=== kliu33/pm2Praktikum/Wintersemester2015/src/aufgabenblatt1/computer.dtd
<!ELEMENT geraete (geraet)*>
<!ELEMENT geraet (sensor)*>
<!ATTLIST geraet name  CDATA #REQUIRED>
<!ATTLIST geraet ip  CDATA #REQUIRED>
<!ELEMENT sensor (ort*,wert*)>
<!ATTLIST sensor typ CDATA #IMPLIED>
<!ELEMENT ort (#PCDATA)>
<!ELEMENT wert (#PCDATA)>

=== kliu33/pm2Praktikum/Wintersemester2015/src/aufgabenblatt1/Rasperry.xml
<?xml version="1.0" ?>
<!DOCTYPE geraete SYSTEM "computer.dtd">
<geraete>
	<geraet name="Raspberry Pi - Model b" ip="192.168.2.1">
		<sensor typ="temperatur">
			<ort>Wohnzimmer</ort>
			<wert>22.4</wert>
		</sensor>
		<sensor>
			<ort>KÃ¼che</ort>
			<wert> -1.2323</wert>
		</sensor>
		<sensor typ="Luftfeuchtigkeit">
			<ort>Badezimmer</ort>
			<wert> 63.8</wert>
		</sensor>
	</geraet>
</geraete>
